### ISSUE TITLE
Add utilities that are currently in ion

### ISSUE THREAD

**Issue by skylerberg** [redox-os/coreutils#1]
Everything that shouldn't be a builtin in ion should be moved here. I took a quick look at the files currently here and what we have in ion. We still need the following from ion:

- [x] echo
- [x] mkdir
- [x] ps
- [x] pwd
- [x] rm
- [x] rmdir
- [x] sleep
- [x] touch

**Comment by polymetric1** [comment]
make those checkboxes e.g.
- [ ] one
- [x] two

**Comment by skylerberg** [comment]
Good idea.

**Comment by hauleth** [comment]
`echo` and `pwd` in 99% are shell built in.

**Comment by Ticki** [comment]
They're both 100% built in.

**Comment by hauleth** [comment]
No 100% as `which echo` and `which pwd` shows that they exist.

**Comment by Ticki** [comment]
```
 ❯ which echo                                                                                                       [15:55:34]
echo: shell built-in command
```

**Comment by hauleth** [comment]
Check /bin/echo

--
Łukasz Jan Niemier

Dnia 11 sty 2016 o godz. 15:55 Ticki <notifications@github.com> napisał(a):

**Comment by Ticki** [comment]
Woah. It's there. Compatibility reasons?

**Comment by hauleth** [comment]
`sh` doesn't have builtin `cat`

**Comment by skylerberg** [comment]
Interesting, I didn't realize these were builtin. I guess we can include them in the shell. I am wondering though, why would these be built into the shell? `pwd` should inherit the environment from the shell so it should be possible to print the current working directory after execing without issues. `echo` and `cat` also don't do any operation that affects the shell's state or depends on the shell's state.

**Comment by Ticki** [comment]
`cat` isn't built in. I'm not sure why `echo` is, though.

**Comment by polymetric1** [comment]
So what should be built in and what shouldn't?

**Comment by jackpot51** [comment]
Build in what cannot be reasonably external. if/else/fi while/do/done come to mind, as well as variable replacement

**Comment by hauleth** [comment]
There should be least possible amount of built-ins. Unless it will be really needed we should keep as much as possible out of the shell. So for now I think it is reasonable to keep all of that out of shell.

@jackpot51 I think we should go with either `end` syntax or `csh`-like. There is no need to keep it legacy with `sh`. We should go with more modern syntax and do not keep with 30 years old legacy.

**Comment by jackpot51** [comment]
I would get rid of `then` and `do`, as ion already does, and using `end` for both sounds good.

Syntax should be
```
if command that returns either zero for true or non-zero for false
    more commands
else
    other commands
end

while command
    more commands
end
```

Putting it on one line, you just add a semicolon:

```
if true; echo yes; else; echo no; end
while true; echo yes; end
```

**Comment by polymetric1** [comment]
Makes sense. There should probably be a compatibility mode for standard scripts, though. This discussion is more for ion though

**Comment by Ticki** [comment]
Why not use curly braces instead? They're much more readable.

**Comment by hauleth** [comment]
Like I said `csh`-like syntax. It would even feel like writing REPL Rust.

**Comment by Ticki** [comment]
We cannot do it half. Either we have to go all in POSIX with Ion, or else we should invent our own syntax. Using compatibility as an argument is invalid in this case.

**Comment by jackpot51** [comment]
I agree. If you are going to break compatibility anyways, do whatever you think is right:

```
if command {
    echo yes
    echo brackets allowed inside of quotes "{}"
} else {
    echo no
}
if command { echo one; echo two; echo three } else { echo one; echo two; echo three }
```

**Comment by polymetric1** [comment]
Posix and unix are all kind of outdated imo. This new syntax makes alot more sense

**Comment by skylerberg** [comment]
Agreed on not doing compatibility mode for legacy scripts. POSIX shell is a different language and you can run it's scripts with `sh`. Many bash scripts start with a shebang, so we would know to run them with bash.

I personally prefer `end` syntax to curly brace syntax because I feel like it is a better fit for interactive use which is the main point of a shell language. No strong reason pops out to me right now for either approach.

**Comment by skylerberg** [comment]
Let's not make `echo` a builtin. Also, things like `if/else/end` should neither be external nor builtins as they are features of the grammar, not commands.

**Comment by hauleth** [comment]
It is impossible to make `if/else/end` commands for the reason that you stated.

**Comment by polymetric1** [comment]
Good point about the interactivity, however with brackets it could be like:
```
$ if true
> {
> echo yes
> }
> else
> {
> echo no
> }
> end
yes
$ 
```
There might have to still be an `end` command to signal end of the interactive session, though.

**Comment by polymetric1** [comment]
Also, I think we should move this discussion to ion.

**Comment by Ticki** [comment]
`{` would work fine, even in an interactive session.

**Comment by Ticki** [comment]
`end` could be used as a "close all open delimiters" command (to avoid delimiter hell).

**Comment by polymetric1** [comment]
Check off everything except `mkdir`, `rmdir`, `ps`, and `sleep`.

**Comment by jackpot51** [comment]
I completed the remaining 4
