### ISSUE TITLE
How about using this one https://github.com/uutils/coreutils?

### ISSUE THREAD

**Issue by lygstate** [redox-os/coreutils#118]
https://github.com/uutils/coreutils

To reduce the work of redox-os,

**Comment by DaanHoogland** [comment]
We just got a PR merged that reduces the default utils in uutils/coreutils to those that compile with redox-os, so we could opt for that. Some utils still have custom implementation, though.

**Comment by simondesloges** [comment]
Related closed issue: #42

**Comment by lygstate** [comment]
OK< understood.
