### ISSUE TITLE
simpler interface to ArgParser

### ISSUE THREAD

**Issue by DaanHoogland** [redox-os/coreutils#120]
ArgParser now only takes two possible arguments for one option (a &char and a string) and then you need to check for each. Does it make sense to have a list of possible arguments that are either &char or string and to have to only check for a symbolic name or for either of the possibilities to fill the option/set the flag?
```
parser.setflag("gurbling",&'g');
parser.setflag("gurbling","gurblingFlag");
if parser.found("gurbling") {} // == true even when --gurbling is passed on cli (or of course -g or --gurblingFlag)

```

**Comment by jackpot51** [comment]
I think it would make sense

**Comment by stratact** [comment]
No need to keep this open.
