### ISSUE TITLE
dd should read from stdin and write to stdout

### ISSUE THREAD

**Issue by tmccrmck** [redox-os/coreutils#126]
If `dd` is not supplied with `if=` the standard input should be used.

And if it is not supplied with `of=` then standard output should be used.

**Comment by Mojo4242** [comment]
Hi @tmccrmck, do you work on this ? If no, I can make a PR on this.

**Comment by tmccrmck** [comment]
It's all you!

**Comment by Mojo4242** [comment]
Yay! 🎉
