### ISSUE TITLE
`cat` skips last lines with missing line terminators

### ISSUE THREAD

**Issue by xTibor** [redox-os/coreutils#141]
When a file has no line terminator on its last line, it seems `cat` just skips that line.

**Comment by jackpot51** [comment]
It does not. Liner is doing \r, wiping out anything on the last line

**Comment by xTibor** [comment]
Sorry about my wrong diagnosis, it really seemed like a `cat` problem for me. I had some of these terminatorless files which could be printed with GNU `cat` on Linux, but they produced incorrect output on Redox. I was just concerned about the data loss it may have caused.

I close this issue because it's a liner issue then.
