### ISSUE TITLE
No upstream Cargo.lock file.

### ISSUE THREAD

**Issue by thinkingeye** [redox-os/coreutils#145]
Hi,
i am trying to package your coreutils for my nixos (and provide them later to the community) but I need an upstream Cargo.lock file for the deterministic build process in nixos. Can you provide one, please?

**Comment by jackpot51** [comment]
I don't use Cargo.lock files because they prevent upstream bug fixes from being used without changing the downstream.

**Comment by jackpot51** [comment]
You can always fork and add one, if you need it

**Comment by thinkingeye** [comment]
Interesting point. I didn't thought about that.
