### ISSUE TITLE
Add manual pages to all the tools.

### ISSUE THREAD

**Issue by ticki** [redox-os/coreutils#19]
- [x] basename
- [x] cat
- [x] clear
- [x] cp
- [x] cut
- [x] du
- [x] echo
- [x] env
- [x] false
- [x] free
- [x] head
- [x] ls
- [x] mkdir
- [x] mv
- [x] ps
- [x] pwd
- [x] realpath
- [x] reset
- [x] rmdir
- [x] rm
- [x] seq
- [x] shutdown
- [x] sleep
- [x] tail
- [x] test
- [x] touch
- [x] true
- [x] wc
- [x] yes

**Comment by jackpot51** [comment]
Updated for current status

**Comment by ticki** [comment]
Cool.

**Comment by GedRap** [comment]
Will complete the rest of them.
