### ISSUE TITLE
Rm should check paths and abort if some of them are not valid

### ISSUE THREAD

**Issue by suhr** [redox-os/coreutils#36]
This will prevent issues like [removing /usr](https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6f1dafc8beb84f2ac).

**Comment by mmstick** [comment]
I'm working on rewriting rm and I'll add this functionality, since it seems useful.

**Comment by Ticki** [comment]
See [safe-rm](https://github.com/MattEagle/safe-rm).

**Comment by suhr** [comment]
Looks like safe-rm just blacklists some paths while this issue is about aborting if some paths doesn't exist (`/lib/nvidia-current/xorg/xorg` does not exist → abort before doing anything).
Both features are useful though.

**Comment by Dr-Emann** [comment]
I believe the use of `-f` should ignore non-existing paths, though, which wouldn't have stopped removing /usr.

**Comment by suhr** [comment]
I think we also need some less powerful option than `-f`. The option that suppress any prompt but fails on non-existing paths.

**Comment by DaanHoogland** [comment]
So do we have a verdict here? I say we check all paths irrespective of all other options and abort if any of them doesn't exist. For people that are not sure it is easy enough to loop over a list.

**Comment by DaanHoogland** [comment]
btw, I think it is sound behaviour to only execute on completely sane command lines.
