### ISSUE TITLE
Consider reusing rust coreutils?

### ISSUE THREAD

**Issue by Seldaek** [redox-os/coreutils#44]
I'm not sure if you willingly reimplemented these or if you didn't know about the project but https://github.com/uutils/coreutils/tree/master/src has rust impl of many coreutils already. Using these might let you focus on other aspects of the os.

**Comment by Ticki** [comment]
Dup of https://github.com/redox-os/coreutils/issues/42.

**Comment by Seldaek** [comment]
Oh sorry was on my phone and I skipped the due diligence here. Fair enough though :)

**Comment by Ticki** [comment]
np!

**Comment by Ticki** [comment]
np!
