### ISSUE TITLE
`mv` should accept multiple source arguments

### ISSUE THREAD

**Issue by skylerberg** [redox-os/coreutils#49]
We currently support `mv SOURCE DEST`, but we don't support `mv SOURCE... DIRECTORY` in which there are multiple source arguments and the final argument is a directory. In this case, each source argument should be moved to the directory. Examples of where this would be useful:

`mv foo bar baz/`
`mv foo/* bar/` This will be expanded into multiple source arguments.

**Comment by mmstick** [comment]
Already implemented this in https://github.com/redox-os/coreutils/pull/50 for both `mv` and `cp`. However, it seems that Redox does not currently work with the `walkdir` crate which is needed for walking directories to copy/move directories and files to a different device. When implemented, you will be able to do things like so:

```
mv -i -v first-file.ext second-file.ext third-file.ext directory/
mv /tmp/dir .
mv . /tmp/
mv file ../../../
mv source/* target/
```

**Comment by jackpot51** [comment]
Stratact has implemented this now
