### ISSUE TITLE
Use clap for parsing options

### ISSUE THREAD

**Issue by hauleth** [redox-os/coreutils#66]
It would make code much easier to read.

**Comment by rushsteve1** [comment]
True it would make code easier to read, but it would add a large unnecessary dependency to the project as a whole.

These utilities are supposed to be as small and self-contained as possible. A whole massive library just to save a few lines is not worth it.

**Comment by jackpot51** [comment]
I agree with @rushstrve1

**Comment by rushsteve1** [comment]
@jackpot51 can we mark this as Wont Fix and close it?

**Comment by jackpot51** [comment]
Ok
