### ISSUE TITLE
Command Line Argument Parser

### ISSUE THREAD

**Issue by msehnout** [redox-os/coreutils#71]
So far every utility does argument parsing on its own. It'd be nice to have one standardized way.

I found these crates:
https://github.com/kbknapp/clap-rs
https://github.com/tailhook/rust-argparse
https://github.com/docopt/docopt.rs

**Comment by hauleth** [comment]
I am big fan of clap. Together with docopt great thing is that they allow parsing help info and parse opts based on this.

**Comment by kc1212** [comment]
Looks like this just got implemented 4ebc2ed59c7111133f70033aae9208a507d8d709

**Comment by DaanHoogland** [comment]
As stated ArgParser is the standard now.
