### ISSUE TITLE
Date Formatting

### ISSUE THREAD

**Issue by rushsteve1** [redox-os/coreutils#73]
The `date` command currently just prints the unix timestamp, and while this works for basic functionality we should look into using something like [rust-chrono](https://github.com/lifthrasiir/rust-chrono) or our own implementation to format it into a human readable format.

**Comment by efyang** [comment]
So if I were to use rust-chrono it would still compile for redox? I could probably take this if so.

**Comment by rushsteve1** [comment]
No idea. That would have to be tested.

**Comment by nbraud** [comment]
@efyang rust-chrono is pure Rust, and it's dependencies are pretty reasonable, so there is no reason it wouldn't build on redox.
As @rushsteve1 said, this should be tested, though.

**Comment by efyang** [comment]
I'll test these later today, but would it also be reasonable to use [clap](https://crates.io/crates/clap) at this point? Rewriting it to basically fit with the BSD format would be much easier to do, and would give a head start on #71. Or should I just keep the current style of handling arguments?

**Comment by rushsteve1** [comment]
@efyang there have already been separate discussions about clap and we have decided not to use it.

**Comment by efyang** [comment]
Ah ok. Just clarifying because #71 is still open.

**Comment by efyang** [comment]
Could I get a few pointers as to how to make the `time` crate use the provided libc? I've added chrono and then time to the main `crates` directory, but I don't know how I should modify the `Cargo.toml` for `time` to use Redox's libc.

**Comment by jackpot51** [comment]
I am taking care of this. Redox does not have full libc support - things like strftime may not work, especially on the new kernel. I used this algorithm to write it in Rust: http://ptspts.blogspot.com/2009/11/how-to-convert-unix-timestamp-to-civil.html
