### ISSUE TITLE
implement `sort` command

### ISSUE THREAD

**Issue by jackpot51** [redox-os/coreutils#79]
There is no `sort` command.

It should sort alphabetically by default, and accept `-n` for sorting numerically

**Comment by nagashayan** [comment]
am interested to contribute, can any body help me get started with initial contribution? Thanks

**Comment by kc1212** [comment]
@nagashayan you can have a look at [here](https://github.com/uutils/coreutils/blob/master/src/sort/sort.rs) for ideas

**Comment by nagashayan** [comment]
@kc1212  I started with it have, some trouble building how can I contact u privately?

**Comment by kc1212** [comment]
Building coreutils or redox? Coreutils is just cargo build, you don't need redox to run the utils.

On 7 October 2016 20:23:07 CEST, Nagashayan <notifications@github.com> wrote:
>@kc1212  I started with it have, some trouble building how can I
>contact u privately? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/redox-os/coreutils/issues/79#issuecomment-252325294

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nagashayan** [comment]
@kc1212 am trying to build coreutils on my mac using cargo, cargo 0.13.0-nightly and have rustc 1.12.0. it throws this error http://pastebin.com/HV9KXBxt . the libextra which is been used is not getting compiled I tried cloning and specifying it as local path, still not able to build.

**Comment by kc1212** [comment]
The error message there says you can't use stable rustc (1.12). I suggest using nightly rust (1.14) because that's how redox is built. A convenient way to install different versions of rust is to use https://rustup.rs/

On 8 October 2016 04:43:13 CEST, Nagashayan <notifications@github.com> wrote:
>@kc1212 am trying to build coreutils on my mac using cargo, cargo
>0.13.0-nightly and have rustc 1.12.0. it throws this error
>http://pastebin.com/HV9KXBxt . the libextra which is been used is not
>getting compiled I tried cloning and specifying it as local path, still
>not able to build. 
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/redox-os/coreutils/issues/79#issuecomment-252397802

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nagashayan** [comment]
Thanks mate. Now am able to build and run commands. started working on issue.

**Comment by kc1212** [comment]
Any news on this @nagashayan? Otherwise I'd like to give it a try.

**Comment by divoxx** [comment]
@kc1212 is this supposed to be a simplified version of sort, supporting the `-n` option or a drop-in replacement for gnu's coreutils?

**Comment by kc1212** [comment]
@divoxx I assume it is the simplified version. But I'm not a redox developer so it's better to ask someone from the redox team.
