### ISSUE TITLE
Fix `mv` and `cp` with directory as source

### ISSUE THREAD

**Issue by jackpot51** [redox-os/coreutils#89]
mv and cp should check if each source argument is a file before continuing, or cp should implement the -R flag and both should use walkdir to mv/cp every file

**Comment by DaanHoogland** [comment]
@jackpot51 looking at this in cp. Can I assign to self?

**Comment by DaanHoogland** [comment]
@jackpot51 do you mean  https://github.com/BurntSushi/walkdir ?

**Comment by DaanHoogland** [comment]
NOTE: follow-symlinks, follow-hardlinks (and other options) will then need to be considered as well

**Comment by DaanHoogland** [comment]
Now I am confused by #49. I will read the source to see if anything still needs doing.

**Comment by DaanHoogland** [comment]
cp is kinda done. just a simple walkdir based on the -r flag, no extensive checkingfor file types and other causes for errors.
Also this solution cannot blindly be copied to mv as it does not need to mind about different file systems, as mv would have to.
